### PR TITLE
Use coursier to get dependencies

### LINKED ISSUE #1139: Find updates of sbt and scalafmt with CoursierAlg
Since #1131 and #1133 we can use `CoursierAlg` to find updates of dependencies. We should also use it to find updates of sbt and scalafmt instead of doing it in `SbtAlg` via `withTemporarySbtDependency`.

### PR DESCRIPTION
**Pull request by manuelcueto**
closes #1139 

What do you think @fthomas ?

Would this `(UpdateAlg.findUpdateUnderNewGroup)` in line 115 have to be reimplemented?

### CODE REVIEW

**Comment by fthomas** [comment]
If we want to get rid of `getUpdatesForRepo`, we need to have #1141 first so that we also find updates of dependencies that are only in private repositories. My intention with #1139 was to only replace `withTemporarySbtDependency` with `UpdateAlg.findUpdate`. `withTemporarySbtDependency` allows us to also get updates of `org.scala-sbt:sbt` and `org.scalameta:scalafmt-core` which are then used to update the sbt version in `project/build.properties` and the scalafmt version in `.scalafmt.conf`. To find updates of these two dependencies, support for custom repositories in `CoursierAlg` is not needed.

**Comment by manuelcueto** [comment]
Ohh i see. I first tried calling findUpdate from SbtAlg but i couldn't create it because it was creating a Circular Dependency.

**Comment by fthomas** [comment]
Oh, I didn't noticed that there would be circular dependency if `findUpdate` is used in `SbtAlg`. Which class is causing it?

**Comment by manuelcueto** [comment]
RepoCacheAlg needs SbtAlg And UpdateAlg needs RepoCacheAlg 
so SbtAlg cannot need UpdateAlg

**Comment by fthomas** [comment]
I think we should split `UpdateAlg` into two classes. One contains `findUpdate`, `findUpdateUnderNewGroup`, and `getNewerGroupId` and the other one the rest which just exists for the "pruning repos" implementation.

**Comment by fthomas** [comment]
Superseded by #1209.

**Pull request closed without merging**
