### PR TITLE
Fix createPullRequests with Gitlab --do-not-fork option

### PR DESCRIPTION
**Pull request by daddykotex**
see https://github.com/fthomas/scala-steward/issues/689

### CODE REVIEW

**Comment by tyrcho** [comment]
Hi,

I just tested on [daddykotex:daddykotex/gitlab/fix-create-mr](https://github.com/daddykotex/scala-steward/tree/daddykotex/gitlab/fix-create-mr)
with these arguments:
```
-DROOT_LOG_LEVEL=DEBUG -DLOG_LEVEL=DEBUG

--workspace "/data/workspace/" --disable-sandbox --do-not-fork --repos-file "/data/repos.md" --git-author-name "Scala Steward" --git-author-email "gitlab@colisweb.com" --vcs-type "gitlab" --vcs-api-host "https://gitlab.com/api/v4/" --vcs-login "tyrcho" --git-ask-pass "/data/pass.sh"
```

```
cat /data/repos.md
- colisweb/pocs/quickstart-scala
```

And it failed.

Here are the logs:

```
/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin/java -Dvisualvm.id=1615324924326239 -DROOT_LOG_LEVEL=DEBUG -DLOG_LEVEL=DEBUG "-javaagent:/Users/michel/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/191.6183.87/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=54621:/Users/michel/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/191.6183.87/IntelliJ IDEA CE.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/lib/tools.jar:/Users/michel/git/katas/scala-steward/modules/core/.jvm/target/scala-2.12/classes:/Users/michel/.ivy2/cache/org.typelevel/macro-compat_2.12/jars/macro-compat_2.12-1.1.1.jar:/Users/michel/.ivy2/cache/org.typelevel/machinist_2.12/jars/machinist_2.12-0.6.6.jar:/Users/michel/.ivy2/cache/org.typelevel/jawn-parser_2.12/jars/jawn-parser_2.12-0.14.1.jar:/Users/michel/.ivy2/cache/org.typelevel/cats-macros_2.12/jars/cats-macros_2.12-1.6.1.jar:/Users/michel/.ivy2/cache/org.typelevel/cats-kernel_2.12/jars/cats-kernel_2.12-1.6.1.jar:/Users/michel/.ivy2/cache/org.typelevel/cats-free_2.12/jars/cats-free_2.12-1.1.0.jar:/Users/michel/.ivy2/cache/org.typelevel/cats-effect_2.12/jars/cats-effect_2.12-1.3.1.jar:/Users/michel/.ivy2/cache/org.typelevel/cats-core_2.12/jars/cats-core_2.12-1.6.1.jar:/Users/michel/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.25.jar:/Users/michel/.ivy2/cache/org.scodec/scodec-bits_2.12/jars/scodec-bits_2.12-1.1.11.jar:/Users/michel/.ivy2/cache/org.scala-lang.modules/scala-xml_2.12/bundles/scala-xml_2.12-1.2.0.jar:/Users/michel/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.12.8.jar:/Users/michel/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.12.8.jar:/Users/michel/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.12.8.jar:/Users/michel/.ivy2/cache/org.log4s/log4s_2.12/jars/log4s_2.12-1.8.2.jar:/Users/michel/.ivy2/cache/org.http4s/parboiled_2.12/jars/parboiled_2.12-1.0.1.jar:/Users/michel/.ivy2/cache/org.http4s/jawn-fs2_2.12/jars/jawn-fs2_2.12-0.14.2.jar:/Users/michel/.ivy2/cache/org.http4s/http4s-jawn_2.12/jars/http4s-jawn_2.12-0.20.6.jar:/Users/michel/.ivy2/cache/org.http4s/http4s-core_2.12/jars/http4s-core_2.12-0.20.6.jar:/Users/michel/.ivy2/cache/org.http4s/http4s-client_2.12/jars/http4s-client_2.12-0.20.6.jar:/Users/michel/.ivy2/cache/org.http4s/http4s-circe_2.12/jars/http4s-circe_2.12-0.20.6.jar:/Users/michel/.ivy2/cache/org.http4s/http4s-blaze-core_2.12/jars/http4s-blaze-core_2.12-0.20.6.jar:/Users/michel/.ivy2/cache/org.http4s/http4s-blaze-client_2.12/jars/http4s-blaze-client_2.12-0.20.6.jar:/Users/michel/.ivy2/cache/org.http4s/blaze-http_2.12/jars/blaze-http_2.12-0.14.6.jar:/Users/michel/.ivy2/cache/org.http4s/blaze-core_2.12/jars/blaze-core_2.12-0.14.6.jar:/Users/michel/.ivy2/cache/org.eclipse.jetty.alpn/alpn-api/jars/alpn-api-1.1.3.v20160715.jar:/Users/michel/.ivy2/cache/io.circe/circe-refined_2.12/jars/circe-refined_2.12-0.11.1.jar:/Users/michel/.ivy2/cache/io.circe/circe-parser_2.12/jars/circe-parser_2.12-0.11.1.jar:/Users/michel/.ivy2/cache/io.circe/circe-numbers_2.12/jars/circe-numbers_2.12-0.11.1.jar:/Users/michel/.ivy2/cache/io.circe/circe-jawn_2.12/jars/circe-jawn_2.12-0.11.1.jar:/Users/michel/.ivy2/cache/io.circe/circe-generic_2.12/jars/circe-generic_2.12-0.11.1.jar:/Users/michel/.ivy2/cache/io.circe/circe-generic-extras_2.12/jars/circe-generic-extras_2.12-0.11.1.jar:/Users/michel/.ivy2/cache/io.circe/circe-core_2.12/jars/circe-core_2.12-0.11.1.jar:/Users/michel/.ivy2/cache/io.circe/circe-config_2.12/jars/circe-config_2.12-0.6.1.jar:/Users/michel/.ivy2/cache/io.chrisdavenport/vault_2.12/jars/vault_2.12-1.0.0.jar:/Users/michel/.ivy2/cache/io.chrisdavenport/unique_2.12/jars/unique_2.12-1.0.0.jar:/Users/michel/.ivy2/cache/io.chrisdavenport/log4cats-slf4j_2.12/jars/log4cats-slf4j_2.12-0.3.0.jar:/Users/michel/.ivy2/cache/io.chrisdavenport/log4cats-core_2.12/jars/log4cats-core_2.12-0.3.0.jar:/Users/michel/.ivy2/cache/eu.timepit/refined_2.12/jars/refined_2.12-0.9.8.jar:/Users/michel/.ivy2/cache/eu.timepit/refined-cats_2.12/jars/refined-cats_2.12-0.9.8.jar:/Users/michel/.ivy2/cache/commons-io/commons-io/jars/commons-io-2.6.jar:/Users/michel/.ivy2/cache/com.typesafe/config/bundles/config-1.3.3.jar:/Users/michel/.ivy2/cache/com.twitter/hpack/jars/hpack-1.0.2.jar:/Users/michel/.ivy2/cache/com.github.pathikrit/better-files_2.12/jars/better-files_2.12-3.8.0.jar:/Users/michel/.ivy2/cache/com.github.julien-truffaut/newts-core_2.12/jars/newts-core_2.12-0.3.1.jar:/Users/michel/.ivy2/cache/com.github.julien-truffaut/monocle-core_2.12/jars/monocle-core_2.12-1.5.1-cats.jar:/Users/michel/.ivy2/cache/com.github.alexarchambault/case-app_2.12/jars/case-app_2.12-2.0.0-M9.jar:/Users/michel/.ivy2/cache/com.github.alexarchambault/case-app-util_2.12/jars/case-app-util_2.12-2.0.0-M9.jar:/Users/michel/.ivy2/cache/com.github.alexarchambault/case-app-annotations_2.12/jars/case-app-annotations_2.12-2.0.0-M9.jar:/Users/michel/.ivy2/cache/com.chuusai/shapeless_2.12/bundles/shapeless_2.12-2.3.3.jar:/Users/michel/.ivy2/cache/co.fs2/fs2-io_2.12/jars/fs2-io_2.12-1.0.5.jar:/Users/michel/.ivy2/cache/co.fs2/fs2-core_2.12/jars/fs2-core_2.12-1.0.5.jar:/Users/michel/.ivy2/cache/ch.qos.logback/logback-core/jars/logback-core-1.2.3.jar:/Users/michel/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.2.3.jar org.scalasteward.core.application.StewardAlg run --workspace /data/workspace/ --disable-sandbox --do-not-fork --repos-file /data/repos.md --git-author-name "Scala Steward" --git-author-email gitlab@colisweb.com --vcs-type gitlab --vcs-api-host https://gitlab.com/api/v4/ --vcs-login tyrcho --git-ask-pass /data/pass.sh
2019-07-18 18:24:55,321 INFO  Add global sbt plugins
2019-07-18 18:24:55,393 INFO  Clean workspace /data/workspace
2019-07-18 18:24:55,502 INFO  ──────────── Nurture colisweb/pocs/quickstart-scala ────────────
2019-07-18 18:24:55,504 INFO  Clone and synchronize colisweb/pocs/quickstart-scala
2019-07-18 18:24:56,145 DEBUG Requesting connection: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
2019-07-18 18:24:56,153 DEBUG Active connection not found. Creating new one. curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
2019-07-18 18:24:56,653 DEBUG Starting up.
2019-07-18 18:24:56,653 DEBUG Stage ByteBufferHead sending inbound command: Connected
2019-07-18 18:24:56,653 DEBUG Starting up.
2019-07-18 18:24:56,653 DEBUG Stage SSLStage sending inbound command: Connected
2019-07-18 18:24:56,654 DEBUG Stage started up. Beginning read buffering
2019-07-18 18:24:56,700 DEBUG SSL Read Request Status: Status = OK HandshakeStatus = NEED_WRAP
bytesConsumed = 0 bytesProduced = 0, java.nio.HeapByteBuffer[pos=0 lim=16921 cap=16921]
2019-07-18 18:24:56,708 DEBUG Stage ReadBufferStage sending inbound command: Connected
2019-07-18 18:24:56,708 DEBUG Starting up.
2019-07-18 18:24:56,736 DEBUG Starting up.
2019-07-18 18:24:56,736 DEBUG Starting response header timeout stage with timeout of 10000 ms
2019-07-18 18:24:56,739 DEBUG Connection was idle. Running.
2019-07-18 18:24:56,739 DEBUG Beginning request: GET https://gitlab.com/api/v4/projects/colisweb%2Fpocs%2Fquickstart-scala
2019-07-18 18:24:56,779 DEBUG Starting idle timeout stage with timeout of 60000 ms
2019-07-18 18:24:57,144 DEBUG SSL Read Request Status: Status = BUFFER_UNDERFLOW HandshakeStatus = NOT_HANDSHAKING
bytesConsumed = 0 bytesProduced = 0, java.nio.HeapByteBuffer[pos=0 lim=16921 cap=16921]
2019-07-18 18:24:57,484 DEBUG SSL Read Request Status: Status = OK HandshakeStatus = NOT_HANDSHAKING
bytesConsumed = 3222 bytesProduced = 3193, java.nio.HeapByteBuffer[pos=3193 lim=16921 cap=16921]
2019-07-18 18:24:57,484 DEBUG SSL Read Request Status: Status = BUFFER_UNDERFLOW HandshakeStatus = NOT_HANDSHAKING
bytesConsumed = 0 bytesProduced = 0, java.nio.HeapByteBuffer[pos=0 lim=16921 cap=16921]
2019-07-18 18:24:57,484 DEBUG SSL Read Request Status: Status = BUFFER_UNDERFLOW HandshakeStatus = NOT_HANDSHAKING
bytesConsumed = 0 bytesProduced = 0, java.nio.HeapByteBuffer[pos=0 lim=16921 cap=16921]
2019-07-18 18:24:57,587 DEBUG Resetting org.http4s.client.blaze.Http1Connection after completing request.
2019-07-18 18:24:57,595 DEBUG Shutting down response header timeout stage
2019-07-18 18:24:57,595 DEBUG Shutting down.
2019-07-18 18:24:57,595 DEBUG Removed mid-stage: ResponseHeaderTimeoutStage
2019-07-18 18:24:57,727 DEBUG Shutting down idle timeout stage
2019-07-18 18:24:57,728 DEBUG Shutting down.
2019-07-18 18:24:57,728 DEBUG Removed mid-stage: IdleTimeoutStage
2019-07-18 18:24:57,730 DEBUG Shutting down.
2019-07-18 18:24:57,734 DEBUG Error while closing SSL Engine
javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1647)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1615)
	at sun.security.ssl.SSLEngineImpl.closeInbound(SSLEngineImpl.java:1542)
	at org.http4s.blaze.pipeline.stages.SSLStage.stageShutdown(SSLStage.scala:61)
	at org.http4s.blaze.pipeline.Tail.closePipeline(Stages.scala:78)
	at org.http4s.blaze.pipeline.Tail.closePipeline$(Stages.scala:77)
	at org.http4s.blaze.pipeline.stages.SSLStage.closePipeline(SSLStage.scala:41)
	at org.http4s.blaze.pipeline.Tail.closePipeline(Stages.scala:81)
	at org.http4s.blaze.pipeline.Tail.closePipeline$(Stages.scala:77)
	at org.http4s.client.blaze.ReadBufferStage.closePipeline(ReadBufferStage.scala:13)
	at org.http4s.blaze.pipeline.Tail.closePipeline(Stages.scala:81)
	at org.http4s.blaze.pipeline.Tail.closePipeline$(Stages.scala:77)
	at org.http4s.client.blaze.Http1Connection.closePipeline(Http1Connection.scala:25)
	at org.http4s.client.blaze.Http1Connection.shutdownWithError(Http1Connection.scala:83)
	at org.http4s.client.blaze.Http1Connection.stageShutdown(Http1Connection.scala:54)
	at org.http4s.client.blaze.Http1Connection.shutdown(Http1Connection.scala:52)
	at org.http4s.client.PoolManager.$anonfun$invalidate$1(PoolManager.scala:313)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:87)
	at cats.effect.internals.IORunLoop$.startCancelable(IORunLoop.scala:41)
	at cats.effect.internals.IOBracket$BracketStart.run(IOBracket.scala:86)
	at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:70)
	at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:36)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
	at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:44)
	at cats.effect.internals.Callback$AsyncIdempotentCallback.apply(Callback.scala:133)
	at cats.effect.internals.Callback$AsyncIdempotentCallback.apply(Callback.scala:120)
	at org.http4s.client.blaze.Http1Connection.parsePrelude(Http1Connection.scala:296)
	at org.http4s.client.blaze.Http1Connection.$anonfun$readAndParsePrelude$1(Http1Connection.scala:189)
	at org.http4s.client.blaze.Http1Connection.$anonfun$readAndParsePrelude$1$adapted(Http1Connection.scala:188)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
2019-07-18 18:24:57,735 DEBUG Shutting down.
2019-07-18 18:24:57,736 DEBUG doClosePipeline(None)
2019-07-18 18:24:57,736 DEBUG Shutting down.
2019-07-18 18:24:57,739 DEBUG Invalidated connection, no pending requests. Shrinking pool: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
2019-07-18 18:24:57,742 ERROR ──────────── Nurture colisweb/pocs/quickstart-scala ──────────── failed
org.http4s.InvalidMessageBodyFailure: Invalid message body: Could not decode JSON: {
  "id" : 12211386,
  "description" : "",
  "name" : "quickstart-scala",
  "name_with_namespace" : "Colisweb / pocs / quickstart-scala",
  "path" : "quickstart-scala",
  "path_with_namespace" : "colisweb/pocs/quickstart-scala",
  "created_at" : "2019-05-07T12:27:50.511Z",
  "default_branch" : "master",
  "tag_list" : [
  ],
  "ssh_url_to_repo" : "git@gitlab.com:colisweb/pocs/quickstart-scala.git",
  "http_url_to_repo" : "https://gitlab.com/colisweb/pocs/quickstart-scala.git",
  "web_url" : "https://gitlab.com/colisweb/pocs/quickstart-scala",
  "readme_url" : "https://gitlab.com/colisweb/pocs/quickstart-scala/blob/master/README.md",
  "avatar_url" : null,
  "star_count" : 0,
  "forks_count" : 0,
  "last_activity_at" : "2019-07-18T13:51:08.308Z",
  "namespace" : {
    "id" : 3516177,
    "name" : "pocs",
    "path" : "pocs",
    "kind" : "group",
    "full_path" : "colisweb/pocs",
    "parent_id" : 3054234,
    "avatar_url" : null,
    "web_url" : "https://gitlab.com/groups/colisweb/pocs"
  },
  "_links" : {
    "self" : "https://gitlab.com/api/v4/projects/12211386",
    "issues" : "https://gitlab.com/api/v4/projects/12211386/issues",
    "merge_requests" : "https://gitlab.com/api/v4/projects/12211386/merge_requests",
    "repo_branches" : "https://gitlab.com/api/v4/projects/12211386/repository/branches",
    "labels" : "https://gitlab.com/api/v4/projects/12211386/labels",
    "events" : "https://gitlab.com/api/v4/projects/12211386/events",
    "members" : "https://gitlab.com/api/v4/projects/12211386/members"
  },
  "empty_repo" : false,
  "archived" : false,
  "visibility" : "private",
  "resolve_outdated_diff_discussions" : false,
  "container_registry_enabled" : true,
  "issues_enabled" : true,
  "merge_requests_enabled" : true,
  "wiki_enabled" : true,
  "jobs_enabled" : true,
  "snippets_enabled" : true,
  "issues_access_level" : "enabled",
  "repository_access_level" : "enabled",
  "merge_requests_access_level" : "enabled",
  "wiki_access_level" : "enabled",
  "builds_access_level" : "enabled",
  "snippets_access_level" : "enabled",
  "shared_runners_enabled" : true,
  "lfs_enabled" : true,
  "creator_id" : 188924,
  "import_status" : "none",
  "import_error" : null,
  "open_issues_count" : 0,
  "runners_token" : "iEuWyZxSC8TagzBSQyiJ",
  "ci_default_git_depth" : null,
  "public_jobs" : true,
  "build_git_strategy" : "fetch",
  "build_timeout" : 3600,
  "auto_cancel_pending_pipelines" : "enabled",
  "build_coverage_regex" : null,
  "ci_config_path" : null,
  "shared_with_groups" : [
  ],
  "only_allow_merge_if_pipeline_succeeds" : false,
  "request_access_enabled" : false,
  "only_allow_merge_if_all_discussions_are_resolved" : false,
  "printing_merge_request_link_enabled" : true,
  "merge_method" : "merge",
  "external_authorization_classification_label" : "",
  "auto_devops_enabled" : false,
  "auto_devops_deploy_strategy" : "continuous",
  "permissions" : {
    "project_access" : null,
    "group_access" : {
      "access_level" : 50,
      "notification_level" : 3
    }
  },
  "mirror" : false
}
	at org.http4s.circe.CirceInstances$.$anonfun$defaultJsonDecodeError$1(CirceInstances.scala:191)
	at org.http4s.circe.CirceInstances.$anonfun$jsonOfWithMedia$2(CirceInstances.scala:73)
	at scala.util.Either.fold(Either.scala:192)
	at org.http4s.circe.CirceInstances.$anonfun$jsonOfWithMedia$1(CirceInstances.scala:74)
	at cats.data.EitherT.$anonfun$flatMap$1(EitherT.scala:99)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:139)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:355)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:376)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:316)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:136)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:355)
	at cats.effect.internals.IORunLoop$RestartCallback.run(IORunLoop.scala:366)
	at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:70)
	at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:36)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
	at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:44)
	at cats.effect.internals.Callback$AsyncIdempotentCallback.apply(Callback.scala:133)
	at cats.effect.internals.Callback$AsyncIdempotentCallback.apply(Callback.scala:120)
	at org.http4s.client.blaze.Http1Connection.parsePrelude(Http1Connection.scala:296)
	at org.http4s.client.blaze.Http1Connection.$anonfun$readAndParsePrelude$1(Http1Connection.scala:189)
	at org.http4s.client.blaze.Http1Connection.$anonfun$readAndParsePrelude$1$adapted(Http1Connection.scala:188)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: io.circe.DecodingFailure$$anon$2: Attempt to decode value on failed cursor: DownField(owner)
2019-07-18 18:24:57,748 INFO  ──────────── Total time: colisweb/pocs/quickstart-scala: 2s 242ms ────────────
2019-07-18 18:24:57,750 INFO  ──────────── Total time: run: 2s 432ms ────────────
2019-07-18 18:24:57,750 INFO  Shutting down connection pool: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false

Process finished with exit code 0

```

**Comment by tyrcho** [comment]
I had a similar issue with this project https://gitlab.com/colisweb-open-source/JRubysnessHours

This one is open-source, and also using a gitlab group, so you should be able ro reproduce more easily the issue.

**Comment by daddykotex** [comment]
You have the issue that is fixed by https://github.com/fthomas/scala-steward/pull/722

With that said, I was not aware that you could have `multiple/slash/under-a-repo`. We would have to test that.

**Comment by fthomas** [comment]
I'm a little bit lost now. Is it safe to merge #722 and this PR?

**Comment by daddykotex** [comment]
#722 is safe to merge.
This PR is safe to merge.

Together, the Gitlab integration works with the --do-not-fork.

**Comment by fthomas** [comment]
Thanks, @daddykotex!

**Pull request merged**
