### PR TITLE
Add Migration Rule for ZIO Test

### PR DESCRIPTION
**Pull request by adamgfraser**

### CODE REVIEW

**Comment by adamgfraser** [comment]
Hi @fthomas. First, thank you for the fantastic software! We use Scala Steward throughout the ZIO ecosystem and it has been great for keeping our dependencies up to date. This is the first Scalafix migration rule we have added so would appreciate if you could take a look and make sure I have not done anything obviously wrong. We are currently on RC17 and want this rewrite rule to be run for updates to RC18 when it is released. Thanks again and hope you are having a great day!

**Comment by adamgfraser** [comment]
Thanks so much! Just so I understand is this migration rule "live" now or do we have to wait for the next release of Scala Steward?

**Comment by fthomas** [comment]
@adamgfraser My public Scala Steward instance tracks the master branch so yes, this migration is live now.

**Comment by adamgfraser** [comment]
@fthomas Awesome!

**Comment by fthomas** [comment]
FTR, here are the PRs where Scala Steward applied this migration:
https://github.com/pulls?page=1&q=author%3Ascala-steward+is%3Apr+%22github%3Azio%2Fzio%2FCurriedAssert%22

**Pull request merged**
