### PR TITLE
Add migration for http4s 0.20

### PR DESCRIPTION
**Pull request by fthomas**

### CODE REVIEW

**Comment by fthomas** [comment]
Here is the referenced rule: https://github.com/http4s/http4s/blob/master/scalafix/rules/src/main/scala/fix/v0_20.scala

**Comment by fthomas** [comment]
Here is this PR in action: https://github.com/fthomas/scalafix-test/pull/8/files

**Comment by fthomas** [comment]
What is currently unclear to me is how to determine the list of artifactIds from looking at the rewrite rules. The easiest for me would be to run this migration when any artifactId of the update matches `http4s-.*` @amarrella do you have any insights which artifactIds we should list here?

**Comment by amarrella** [comment]
I *think* you can safely target all artifacts, but the fix will probably mostly used for clients and server?

**Comment by fthomas** [comment]
Thanks for the confirmation, @amarrella. The migration targets now all `http4s-.*` artifacts because I found it too tedious to list all applicable artifacts individually.

**Pull request merged**
