### PR TITLE
 Change updatePullRequests config to be an enum(always, on-conflicts, never)

### PR DESCRIPTION
**Pull request by kiranbayram**
Addresses #1162

### CODE REVIEW

**Comment by kiranbayram** [comment]
I wanted to add some tests for `shouldBeUpdated` function but initializing `NurtureAlg` looked too difficult 😅 . Do you suggest if we extract `shouldBeUpdated` to companion object ?

**Comment by fthomas** [comment]
Thanks @kiranbayram, this looks good! I only find the name of the flag a little bit unwieldy. While thinking about another name, I had the idea of reusing `updatePullRequests` for this. Instead of being a boolean value, it could be an enum with the values `always`, `never`, and `on-conflicts`:
```
always       would be same as updatePullRequests = true and checkConflictsWhenUpdatingPRs = false
on-conflicts would be same as updatePullRequests = true and checkConflictsWhenUpdatingPRs = true
never        would be same as updatePullRequests = false
```
I feel that this is simpler for users than two interacting boolean flags. The implementation would get a little bit more complex, since we should still allow `true` and `false` as values and map them to `on-conflicts` and `never` to keep current `.scala-steward.conf` files valid. WDYT? Does this makes sense and would you be interested in changing this PR in this direction? If not, we can also merge this now and I'll make the changes later.

**Comment by kiranbayram** [comment]
Makes sense. I'll try to change the PR :+1:

**Comment by fthomas** [comment]
Awesome, thanks!

**Comment by kiranbayram** [comment]
Just finished the implementation, hopefully this is not far from what you had in mind @fthomas

**Comment by fthomas** [comment]
This looks great! Many thanks again, @kiranbayram! I'll merge it tomorrow.

**Comment by mzuehlke** [comment]
This closes #1162

**Comment by fthomas** [comment]
Thanks for the reminder, @mzuehlke. I'm closing that now.

**Pull request merged**
