### PR TITLE
Label PR so users can automate their workflow depending on update type.

### LINKED ISSUE #404: Add labels to pull requests
It would be nice to classify a pull request by adding

- Library update
- Sbt plugin update
- Test library update

Such that you could do automatic patch releases by using mergify (auto-merge) + rancher (auto-tag) + sbt-release-early. I would only release a new artifact if there is a Library update

### PR DESCRIPTION
**Pull request by exoego**
Closes #404 

Added the below labels

* `sbt-plugin-update`
   * sbt plugins,  example PRs: [scala-js](https://github.com/exoego/scala-steward-test-project/pull/113) and [sbt-salafmt](https://github.com/exoego/scala-steward-test-project/pull/115)
   * scalafmt versions in `.scalafmt.conf`, example PR: https://github.com/exoego/scala-steward-test-project/pull/116
   * sbt itself, example PR: https://github.com/exoego/scala-steward-test-project/pull/104
* `test-library-update`
    * Example PRs: [scalatest](https://github.com/exoego/scala-steward-test-project/pull/119) and [scalacheck](https://github.com/exoego/scala-steward-test-project/pull/118)
* Otherwise `library-update`
    * Example PRs: [circe](https://github.com/exoego/scala-steward-test-project/pull/111) and [groovy](https://github.com/exoego/scala-steward-test-project/pull/112)

### CODE REVIEW

**Comment by exoego** [comment]
@fthomas 
Could you kindly give priority to reviewing this PR ?
This PR got conflicted many times for last 3 months.

**Comment by fthomas** [comment]
I'm sorry @exoego that this takes so long, I'll try to find some time to review this. Working on and keeping Scala Steward running is a lot of fun but also a lot of work and it isn't always easy to prioritize the work besides my family life and my day job.

**Comment by fthomas** [comment]
@exoego It seems that this PR only changes the `Update`s that are found in `UpdateAlg`. But these objects are only used to determine on which repos Scala Steward needs to work on when `--prune-repos` is `true` and they are not used when creating the PRs. [`SbtAlg.getUpdatesForRepo`](https://github.com/fthomas/scala-steward/blob/1f43e8f7ee9dcd25d13f8679303ecd5c595c8f70/modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala#L76) returns the `Update`s that are used for creating PRs.

If we want to differentiate between project and build updates we need to split sbt's output in `getUpdatesForRepo` at the `reload plugins` line. Updates before that are project updates and updates after that are build updates. In https://github.com/fthomas/scala-steward/pull/851/commits/61d92404ce654065930cb1e82f14b8242977142d (which is part of https://github.com/fthomas/scala-steward/pull/851) I tried to label updates based on a string that is passed to a new sbt task for finding updates. It could be used like this:
```
sbt ";show stewardDependenciesWithUpdates project;reload plugins; show stewardDependenciesWithUpdates build"
```
This would return a JSON representation of dependencies and updates which are either labeled `project` or `build`. I find this approach cleaner than splitting sbt's output in two parts but it depends on these new sbt tasks. I think it makes sense to wait until #851 is merged and then change this PR to label updates accordingly. WDYT?

**Comment by exoego** [comment]
OK, I will revisit after #851 merged.

**Comment by fthomas** [comment]
FYI: #851 is not merged yet (and probably won't ever be because it was broken up into several other PRs) but similar new `StewardPlugin` tasks were added in #1116. That PR didn't contain the change to label dependencies / updates but adding this feature again should be straightforward. So I'd consider this PR not blocked by me anymore. :-)

**Comment by atapin** [comment]
@fthomas @exoego 
What is the status of this PR? Is abandoned? Any help needed?

**Comment by exoego** [comment]
I will rework this within this week.

**Comment by exoego** [comment]
@fthomas 
I think it is ready to get reviewed.

**Pull request merged**
