### PR TITLE
Mill

### PR DESCRIPTION
**Pull request by hamnis**
Mill Build support.

We need a plugin published which we can call to get the metadata we need.

To test:
* Follow description by https://github.com/fthomas/scala-steward/pull/1478#issuecomment-643218243
* Run `sbt mill/publishLocal runSteward`

### CODE REVIEW

**Comment by fthomas** [comment]
Awesome, @hamnis!

I'm using the `runSteward` sbt command for testing. You need to
 * replace the content of `repos.md` with your test repo
 * add a `.github/askpass/scala-steward.sh` that echos an access token for your GitHub user
 * change the value of the [`--vcs-login` parameter](https://github.com/fthomas/scala-steward/blob/5768b6b01ef6afd868772c96a675e7a5d010c5a4/build.sbt#L240) to your GitHub user

**Comment by hamnis** [comment]
Test run successfully here: https://github.com/hamnis/requests-scala/pull/1/files

**Comment by hamnis** [comment]
@fthomas Could you please have a look and maybe advice on how to deal with the mill plugin. Should that be moved to a separate repo, or is this fine? it will need to be published for mill to be able to resolve it.

**Comment by fthomas** [comment]
Having the mill plugin in this repo is fine with me for now. I can publish it locally before running Scala Steward. If we find that it causes problems, we can always move it to its own repository under the scala-steward-org organization later.

**Comment by fthomas** [comment]
@hamnis Each push to master triggers a release of a snapshot to https://oss.sonatype.org/content/repositories/snapshots (e.g. https://oss.sonatype.org/content/repositories/snapshots/org/scala-steward/scala-steward-core_2.13/0.6.0-13-3dbe3134-SNAPSHOT/scala-steward-core_2.13-0.6.0-13-3dbe3134-SNAPSHOT.jar). Is Mill able to resolve it from there? If yes, there is no need to publish the plugin locally except for development and testing.

**Comment by hamnis** [comment]
AFAIK Mill does not currently have a link to the snapshot repo, but it could.
If we look at https://github.com/fthomas/scala-steward/pull/1478/files#diff-3ec37adca73af3fc3639946cb4609a94R33
We can add a resolver to sonatype here i think.

**Comment by fthomas** [comment]
If a resolver is added there we must ensure it it only used for the scala-steward-mill plugin and not for the complete build. Otherwise it could influence the updates Scala Steward will find.

**Comment by hamnis** [comment]
Good point. I guess we could add a filter of that as I did for the local cache ?

**Comment by hamnis** [comment]
There might be a way: https://gitter.im/lihaoyi/mill?at=5eec66a4c223cc536a21f437

**Comment by fthomas** [comment]
The build failed because scalafmt complained. I've fixed the formatting by running `sbt fmt`.

**Comment by fthomas** [comment]
Publishing the plugin worked:
> [info] 	published scala-steward-mill_2.13 to https://oss.sonatype.org/content/repositories/snapshots/org/scala-steward/scala-steward-mill_2.13/0.6.0-43-b68c3c15-SNAPSHOT/scala-steward-mill_2.13-0.6.0-43-b68c3c15-SNAPSHOT.jar

from https://travis-ci.com/github/fthomas/scala-steward/jobs/352815263

**Comment by fthomas** [comment]
It is not yet working for me:
```
[info] 2020-06-23 23:00:59,282 INFO  ──────────── Steward lefou/mill-osgi ────────────                                                                                                                                                  
[info] 2020-06-23 23:00:59,285 INFO  Check cache of lefou/mill-osgi                                                                                                                                                                     
[info] 2020-06-23 23:01:00,250 INFO  Refresh cache of lefou/mill-osgi                                                                                                                                                                   
[info] 2020-06-23 23:01:07,189 ERROR Check cache of lefou/mill-osgi failed                                                                                                                                                              
[info] java.io.IOException: 'mill -i -p /home/frank/data/code/scala-steward/core/workspace/repos/lefou/mill-osgi/scala-steward.sc show org.scalasteward.mill.plugin.StewardPlugin/extractDeps' exited with code 1                       
[info] Downloading https://repo1.maven.org/maven2/org/scala-steward/scala-steward-mill-plugin_2.13/0.6.0-49-0f58fcff-20200623-2248-SNAPSHOT/scala-steward-mill-plugin_2.13-0.6.0-49-0f58fcff-20200623-2248-SNAPSHOT.pom                 
[info] Downloaded https://repo1.maven.org/maven2/org/scala-steward/scala-steward-mill-plugin_2.13/0.6.0-49-0f58fcff-20200623-2248-SNAPSHOT/scala-steward-mill-plugin_2.13-0.6.0-49-0f58fcff-20200623-2248-SNAPSHOT.pom                  
[info] Downloading https://repo1.maven.org/maven2/org/scala-steward/scala-steward-mill-plugin_2.13/0.6.0-49-0f58fcff-20200623-2248-SNAPSHOT/scala-steward-mill-plugin_2.13-0.6.0-49-0f58fcff-20200623-2248-SNAPSHOT.pom.sha1            
[info] Downloaded https://repo1.maven.org/maven2/org/scala-steward/scala-steward-mill-plugin_2.13/0.6.0-49-0f58fcff-20200623-2248-SNAPSHOT/scala-steward-mill-plugin_2.13-0.6.0-49-0f58fcff-20200623-2248-SNAPSHOT.pom.sha1             
[info] Downloading https://repo1.maven.org/maven2/org/scala-steward/scala-steward-mill-plugin_2.13/0.6.0-49-0f58fcff-20200623-2248-SNAPSHOT/maven-metadata.xml                                                                          
[info] Downloaded https://repo1.maven.org/maven2/org/scala-steward/scala-steward-mill-plugin_2.13/0.6.0-49-0f58fcff-20200623-2248-SNAPSHOT/maven-metadata.xml                                                                           
[info] Downloading https://repo1.maven.org/maven2/org/scala-steward/scala-steward-mill-plugin_2.13/0.6.0-49-0f58fcff-20200623-2248-SNAPSHOT/maven-metadata.xml.sha1                                                                     
[info] Downloaded https://repo1.maven.org/maven2/org/scala-steward/scala-steward-mill-plugin_2.13/0.6.0-49-0f58fcff-20200623-2248-SNAPSHOT/maven-metadata.xml.sha1                                                                      
[info] Failed to resolve ivy dependencies:Error downloading org.scala-steward:scala-steward-mill-plugin_2.13:0.6.0-49-0f58fcff-20200623-2248-SNAPSHOT
[info]   not found: /home/frank/.ivy2/local/org.scala-steward/scala-steward-mill-plugin_2.13/0.6.0-49-0f58fcff-20200623-2248-SNAPSHOT/ivys/ivy.xml
[info]   not found: https://repo1.maven.org/maven2/org/scala-steward/scala-steward-mill-plugin_2.13/0.6.0-49-0f58fcff-20200623-2248-SNAPSHOT/scala-steward-mill-plugin_2.13-0.6.0-49-0f58fcff-20200623-2248-SNAPSHOT.pom
```

**Comment by hamnis** [comment]
Seems like there is something strange when using combination of $ivy import and interp.repositories()

try this:

-       |import $$ivy.`${BuildInfo.organization}::${BuildInfo.millPluginModuleName}:${BuildInfo.version}`""".stripMargin
+       |interp.ivy.load(${BuildInfo.organization} %% ${BuildInfo.millPluginModuleName} % "${BuildInfo.version}")
+       |
+       |""".stripMargin

**Comment by fthomas** [comment]
Using `interp.load.ivy` worked, thanks!

**Comment by lefou** [comment]
@hamnis Scala-Steward create the first two pull requests in my mill based repository and they look perfect. Many thanks for the mill integration!

**Pull request merged**
