### PR TITLE
add checkForUpdate Test and use coursier for getting updates

### LINKED ISSUE #1126: Replace SbtAlg.getUpdatesForProject with coursier.Versions()
Coursier recently added an API to list versions of a module, see https://github.com/coursier/coursier/pull/1439. It seems to me that this could be used to replace `SbtAlg.getUpdatesForProject` which we're currently using to find updates of all dependencies Scala Steward knows about in order to decide on which repos it should work on. In `getUpdatesForProject` we're writing modules to an artificial sbt project that we then load with sbt and where we call sbt-update's task to find new versions. It seems to me that the new Coursier API allows us to find new versions without executing sbt. And since executing sbt is really slow, this change could make Scala Steward a lot faster (at least if `--prune-repos=true`).

### PR DESCRIPTION
**Pull request by manuelcueto**
closes #1126 
Would like to hear some input in case i missed something!

WDYT @fthomas

### CODE REVIEW

**Comment by fthomas** [comment]
This is cool, many thanks @manuelcueto! I'm going to merge this into a new topic branch and will try it out locally.

**Comment by manuelcueto** [comment]
@fthomas would be nice if you share your results when you do it :)

**Comment by fthomas** [comment]
Of course!

Feel free to open further PRs against the topic branch if you'd like to modify your code.

**Comment by fthomas** [comment]
I just tested this branch with my repos. `checkForUpdates` now takes 10 seconds instead of 3 minutes! This is great!

**Pull request merged**
