### PR TITLE
Add rchain/rchain

### PR DESCRIPTION
**Pull request by lukasz-golebiewski**

### CODE REVIEW

**Comment by fthomas** [comment]
@lukasz-golebiewski All pull requests by @scala-steward in rchain/rchain have been closed by @dzajkowski and @KentShikama. It seems to me that you don't need this service. If this is the case please remove rchain/rchain from repos.md. Thanks!

**Comment by lukasz-golebiewski** [comment]
@fthomas Pull requests were closed because the CI builds didn't kick off. Apparently they were opened using @ArturGajowy 's fork (which he added to this file for test purposes a few months back and afterwards removed it). This fork is old and doesn't contain the `.circleci.yml` yet. See here: https://github.com/scala-steward?utf8=%E2%9C%93&tab=repositories&q=rchain&type=&language=. Could you fix this and continue opening PRs?

**Comment by fthomas** [comment]
@lukasz-golebiewski You're right, this should not have happened and I'll fix it. It is strange that GitHub didn't create a new fork and reused the one from ArturGajowy/rchain.

**Comment by ArturGajowy** [comment]
> doesn't contain the .circleci.yml yet
Just for clarity, Łukasz probably meant `.drone.yml`, as this is what we use :)

**Comment by lukasz-golebiewski** [comment]
Indeed @ArturGajowy , but this irrelevant

**Pull request merged**
