### PR TITLE
Explicitly set Coursier's cache policies

### PR DESCRIPTION
**Pull request by fthomas**
By not using the default cache policies we ensure that `cache` does not
download files if local ones are younger than the TTL.

### CODE REVIEW

**Comment by fthomas** [comment]
It seems that this change fixed my recent problems with Maven Central (#1215, #1216, #1218, and #1253). My expectation that `getVersions` only hits the internet if the cached versions are older than the `cacheTtl` didn't hold because of the default cache policies. By using `LocalUpdateChanging` only, `getVersions` now behaves as I expected.

**Comment by fthomas** [comment]
I dig a little deeper and found that the default cache policies only caused repeated requests to Maven Central for sbt plugins that are not hosted on Central. For sbt plugins Coursier gets the versions from a directory listing (like https://repo1.maven.org/maven2/org/scalameta/sbt-scalafmt_2.12_1.0/) since there is no `maven-metadata.xml`. The result of this listing is cached if the plugin exists, but if it doesn't exist the listing is requested every time the `Versions` API is called, irregardless of the cache's TTL. And since the majority of sbt plugins is not hosted on Central, Scala Steward repeatedly requested (non-existing) directory listings of the sbt plugins of every project for which it then got blocked.

**Comment by mzuehlke** [comment]
Good catch, this is true for artefacts coming from other repos than Maven Central, isn't it? Is this a missing feature / bug in Coursier ? To cache no only the existence but also the absence of an artefact ?

**Comment by fthomas** [comment]
It might be a bug in the case of sbt plugins. I think the absence of normal artifacts is cached.

**Pull request merged**
