### PR TITLE
Improve scalafmt update detection and .scalafmt.conf edit

### LINKED ISSUE #819: Project URLs are missing for sbt and scalafmt
PR #762 and #814 introduced links to the updated artifact project.

However, they lacks support of `sbt` and `scalafmt`, since those dependencies are not actually included in `sbtAlg.getDependencies` therefore their URLs are not fetched by `coursierAlg`.

Examples of PR with no URL
* sbt https://github.com/pathikrit/dijon/pull/37
* scalafmt https://github.com/playframework/playframework/pull/9554

### PR DESCRIPTION
**Pull request by exoego**
Closes #819. 
Suepecedes PR #820 based on same strategy inPR #827 

This PR also simplify how to edit `.scalafmt.conf` in 2nd comit https://github.com/fthomas/scala-steward/commit/1cd67f8ab22449381128a7539e89431af13bd3a1 and 3rd commit https://github.com/fthomas/scala-steward/pull/842/commits/3ea2de6f7167798d8b8c7d33c098f2ee7eb5b2d9
It introduces `Update`-specific `UpdateHeuristic` so `ScalafmtAlg.editScalafmtConf` and special handling in `EditAlg` are no longer required.

### CODE REVIEW

**Comment by fthomas** [comment]
Many thanks @exoego! I think `SbtAlg.getDependencies` also need to be changed to include a scalafmt-core dependency. I didn't use `withTemporarySbtDependency` in `getDependencies` since it seems ridiculous to add a dependency to the build and then ask sbt to give it back to us.

**Comment by exoego** [comment]
@fthomas Updated in https://github.com/fthomas/scala-steward/pull/842/commits/16357befbb90222059ebd1bf856df3a344065243

**Comment by fthomas** [comment]
I just tested this and it fails during the dependency updates check with:
```
[info] [warn]   ::::::::::::::::::::::::::::::::::::::::::::::
[info] [warn]   ::          UNRESOLVED DEPENDENCIES         ::
[info] [warn]   ::::::::::::::::::::::::::::::::::::::::::::::
[info] [warn]   :: org.scalameta#scalafmt-core_2.12.9;2.0.0: not found
[info] [warn]   ::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by exoego** [comment]
@fthomas 
Sorry, I think the below PR fix that
https://github.com/fthomas/scala-steward/pull/843

**Comment by fthomas** [comment]
Ok, now it found the update. But it seems that the new `UpdateHeuristic`didn't updated `.scalafmt.conf`:
```
[info] 2019-08-17 10:51:38,761 INFO  ──────────── Nurture fthomas/fs2-cron ────────────
[info] 2019-08-17 10:51:38,761 INFO  Clone and synchronize fthomas/fs2-cron
[info] 2019-08-17 10:51:41,773 INFO  Find updates for fthomas/fs2-cron
[info] 2019-08-17 10:52:24,475 INFO  Ignore org.scala-lang:scala-library:provided : 2.12.7 -> 2.12.9 -> 2.13.0 (reason: ignored globally)
[info] 2019-08-17 10:52:24,475 INFO  Ignore org.scala-lang:scala-library : 2.12.8 -> 2.12.9 -> 2.13.0 (reason: ignored globally)
[info] 2019-08-17 10:52:24,484 INFO  Found 1 update:
[info]   org.scalameta:scalafmt-core_2.12 : 2.0.0 -> 2.0.1
[info] 2019-08-17 10:52:24,490 INFO  Process update org.scalameta:scalafmt-core_2.12 : 2.0.0 -> 2.0.1
[info] 2019-08-17 10:52:24,814 INFO  Trying heuristic 'strict'
[info] 2019-08-17 10:52:24,831 INFO  Trying heuristic 'original'
[info] 2019-08-17 10:52:24,833 INFO  Trying heuristic 'relaxed'
[info] 2019-08-17 10:52:24,837 INFO  Trying heuristic 'sliding'
[info] 2019-08-17 10:52:24,842 INFO  Trying heuristic 'groupId'
[info] 2019-08-17 10:52:24,845 INFO  Trying heuristic 'specific'
[info] 2019-08-17 10:52:24,851 WARN  No files were changed
[info] 2019-08-17 10:52:24,874 INFO  ──────────── Total time: fthomas/fs2-cron: 46s 113ms ────────────
```

**Comment by exoego** [comment]
This is weird.
This PR passed the below test case (`2.0.0 -> 2.1.0` in `.scalafmt.cof`)https://github.com/fthomas/scala-steward/blob/1718dc26c08df42caf8376bc761c92965218a25f/modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala#L81-L83

**Comment by fthomas** [comment]
Maybe it is how the version is defined in fs2-cron:
```
version=2.0.0
```
The regex could be sensitive to the whitespace around the equals sign.

**Pull request merged**
