### PR TITLE
1141 custom resolver

### LINKED ISSUE #1141: Allow repo specific resolvers in CoursierAlg
`CoursierAlg` currently looks for `pom.xml`s, `ivy.xml`s, and new versions in Coursier's default package repositories and in sbt-plugin-releases. It won't find any of those information for packages that are in repo specific repositories. As a prerequisite to replacing sbt-updates with `CoursierAlg` and to make it more useful in general, we need to change `CoursierAlg` so that it can take custom package repositories (and accompanying credentials) into account.

Here are references to other issues and PRs which make the case for this feature:
* https://github.com/fthomas/scala-steward/issues/1088#issuecomment-552585756
* https://github.com/fthomas/scala-steward/pull/1092
* https://github.com/fthomas/scala-steward/pull/1133#issuecomment-562848761

### PR DESCRIPTION
**Pull request by manuelcueto**
closes #1141 
@fthomas  Let me know what you think about it

Sorry for taking so much time to work on it

### CODE REVIEW

**Comment by fthomas** [comment]
Thanks @manuelcueto, this already looks quite good. I would tweak it a little bit mostly for performance reasons:

* Resolvers should be cached by `RepoCacheAlg` so that we don't need to depend on `SbtAlg` in `PruningAlg`. Executing sbt takes a lot of time and the less we need to call it, the faster Scala Steward will be.

* Since executing sbt takes a lot of time, we should query dependencies and resolvers at the same time. So `SbtAlg.getDependencies` should become `SbtAlg.getDependenciesAndResolvers` which returns `F[(List[Dependency], List[Resolver])]`. I know this is ugly but calling sbt twice when we can call it only once would make Scala Steward unnecessarily slow.

* I would not pass extra resolvers in `findAdditionalUpdates` since sbt and scalafmt are on Maven Central and #1209 will remove that function anyway.

I think these changes doesn't require too much code changes.

**Comment by manuelcueto** [comment]
Makes sense, will take a look at it later.

**Comment by fthomas** [comment]
FYI, I merged master to resolve merge conflicts due to the merge of #1235.

**Comment by manuelcueto** [comment]
Ohh , thought it was up to date :) no worries! let me know what you think

**Comment by fthomas** [comment]
No worries, it was up to date until I merged the other PR. :-)

**Pull request merged**
