### PR TITLE
#377 Add good and bad examples doc for dependency definitions

### PR DESCRIPTION
**Pull request by kiranbayram**
Hi there,

I've decided to put examples to a separate file to keep README file clean. And also this doesn't cover all possible working examples (since there're countless combinations) but i've put a link to UpdateTest if somebody wanted to more possibilities or edge cases which are handled.

Cheers

### CODE REVIEW

**Comment by fthomas** [comment]
Many thanks for this, @kiranbayram! This is much appreciated. What do you think about having this documentation as actual test so that the good and bad examples are always in sync with the code? I fear that if this is not machine checked it will be outdated rather quickly.

**Comment by kiranbayram** [comment]
Yes, you're probably right. I'll try to write an ExampleTest which covers these cases and we can refer to that in Readme

**Comment by kiranbayram** [comment]
It would still be nice to create documentation automatically from this test's output but i don't know how .

**Comment by fthomas** [comment]
We could use mdoc (https://scalameta.org/mdoc/) to have these examples as typechecked documentation.

**Comment by kiranbayram** [comment]
Should we then probably open a feature request for trying that out?

**Comment by fthomas** [comment]
Sounds good to me.

**Pull request merged**
