### PR TITLE
Add repo specific conf link to PR body

### PR DESCRIPTION
**Pull request by kiranbayram**
Addresses #1340 

 - I also changed the title of `Ignore future updates` section because we can use that part for repo specific conf examples

### CODE REVIEW

**Comment by kiranbayram** [comment]
I'm not sure if we want to add some examples inside that section, maybe for the most common cases it might make sense. WDYT? @fthomas

**Comment by fthomas** [comment]
Thanks for the PR, @kiranbayram!

> I'm not sure if we want to add some examples inside that section, maybe for the most common cases it might make sense.

What kind of examples are you thinking of?

**Comment by kiranbayram** [comment]
Maybe one or two examples for `pullRequests.frequency` could be useful, since many people were annoyed about PRs from daily release libraries

**Comment by kiranbayram** [comment]
Added a hint for configuring PR frequency. @fthomas WDYT?

**Comment by fthomas** [comment]
I think these hints are helpful if they are adjusted to the current update or repo so that copy and pasting them can save users some time. If they are static, I feel it is enough if they are only included in the documentation page.

**Comment by kiranbayram** [comment]
Damn, messed up some rebase :(

**Comment by kiranbayram** [comment]
going to open a new pr, closing this one

**Pull request closed without merging**
