### PR TITLE
Improve update naming convention

### LINKED ISSUE #60: Better title for dependencies whose name is part of the groupId
See https://github.com/pdalpra/gh4s/pull/15 for an example.

### PR DESCRIPTION
**Pull request by bhop**
fixes #60

### CODE REVIEW

**Comment by fthomas** [comment]
Thanks @bhop, this looks great. I like that you moved the code into a new file, this will help keeping `Update` clean.

Running `sbt formatAll` and committing should fix the build errors.

**Comment by bhop** [comment]
Looks like `sbt formatAll` fixed the problem. Thanks @fthomas !

**Comment by bhop** [comment]
Not sure how I did it but it says: "bhop closed this 9 minutes ago" :P

**Comment by fthomas** [comment]
@all-contributors please add @pgabara for code, test

**Pull request merged**
