### PR TITLE
do not crash when scalafix migration fails. Fix #1121

### LINKED ISSUE #1121: scala steward job failed with a compilation error for org.scalatest:scalatest : 3.0.8 -> 3.1.0
https://gitlab.com/tyrcho/michel-steward/-/jobs/365504552

``` 
java.io.IOException: 
'sbt -batch -no-colors ;scalafixEnable;scalafix https://raw.githubusercontent.com/scalatest/autofix/e4de53fa40fac423bd64d165ff36bde38ce52388/3.0.x/rules/src/main/scala/org/scalatest/autofix/v3_0_x/RenameDeprecatedPackage.scala;test:scalafix 
https://raw.githubusercontent.com/scalatest/autofix/e4de53fa40fac423bd64d165ff36bde38ce52388/3.0.x/rules/src/main/scala/org/scalatest/autofix/v3_0_x/RenameDeprecatedPackage.scala;scalafix 
https://raw.githubusercontent.com/scalatest/autofix/e4de53fa40fac423bd64d165ff36bde38ce52388/3.1.x/rules/src/main/scala/org/scalatest/autofix/v3_1_x/RewriteDeprecatedNames.scala;test:scalafix 
https://raw.githubusercontent.com/scalatest/autofix/e4de53fa40fac423bd64d165ff36bde38ce52388/3.1.x/rules/src/main/scala/org/scalatest/autofix/v3_1_x/RewriteDeprecatedNames.scala'
exited with code 1
```

The CI job (which simply runs scala steward) failed, I think this exception should be caught by scala steward : it should not rely on scalafix migration to always succeed.

### PR DESCRIPTION
**Pull request by tyrcho**

### CODE REVIEW

**Comment by tyrcho** [comment]
@fthomas is it enough for a first fix for #1121 ?

**Comment by fthomas** [comment]
I'm not sure yet. I'd like to look at all failing Scalafix migrations in my public Scala Steward instance first to make sure they don't fail because Scala Steward does something wrong or stupid. If I merge this now, PRs with failed migrations will be created and there is no way for me to correct mistakes in Scala Steward's Scalafix integration and recreate these PRs then.

**Comment by fthomas** [comment]
Ok, I looked at the failing migrations and there was only one instance which we maybe could fix easily. One project already used sbt-scalafix and when Scala Steward also added it to the build, it failed to load with 
```
error: reference to scalafix is ambiguous;
it is imported twice in the same scope by
...
```
I think we can detect if a build is already using sbt-scalafix and only adding it if it is not already there.

The other failures looked more complicated and it wasn't obvious to me how they could be fixed. So I'm okay with merging this now.

**Comment by tyrcho** [comment]
thank you @fthomas !

**Pull request merged**
