### PR TITLE
Rename scalaz-distributed to scalaz-ziokeeper

### PR DESCRIPTION
**Pull request by mijicd**

### CODE REVIEW

**Comment by fthomas** [comment]
@mijicd scala-steward can't load the scalaz-ziokeeper build anymore. It fails with
```
$ sbt -batch -no-colors ;libraryDependenciesAsJson;reload plugins;libraryDependenciesAsJson
[info] Loading settings from sbt-updates.sbt ...
[info] Loading global plugins from /home/frank/.sbt/1.0/plugins
[info] Updating ProjectRef(uri("file:/home/frank/.sbt/1.0/plugins/"), "global-plugins")...
[info] Done updating.
[info] Compiling 1 Scala source to /home/frank/.sbt/1.0/plugins/target/scala-2.12/sbt-1.0/classes ...
[info] Done compiling.
[info] Loading settings from plugins.sbt ...
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /home/frank/.sbt/1.0/staging/0b78e046ed2c8c130506/scalaz-sbt/project
[info] Updating ProjectRef(uri("file:/home/frank/.sbt/1.0/staging/0b78e046ed2c8c130506/scalaz-sbt/project/"), "scalaz-sbt-build")...
[info] Done updating.
[info] Loading settings from build.sbt ...
[info] Loading project definition from /home/frank/code/scala-steward/workspace/repos/scalaz/scalaz-ziokeeper/project
[info] Updating ProjectRef(uri("git:https://github.com/scalaz/scalaz-sbt.git"), "scalaz-sbt")...
[info] Done updating.
[info] Updating ProjectRef(uri("file:/home/frank/code/scala-steward/workspace/repos/scalaz/scalaz-ziokeeper/project/"), "scalaz-ziokeeper-build")...
[info] Done updating.
/home/frank/code/scala-steward/workspace/repos/scalaz/scalaz-ziokeeper/build.sbt:12: error: No implicit for Remove.Value[explicitdeps.ModuleFilter, sbt.librarymanagement.ModuleFilter] found,
  so sbt.librarymanagement.ModuleFilter cannot be removed from explicitdeps.ModuleFilter
    unusedCompileDependenciesFilter -= moduleFilter("com.github.ghik", "silencer-lib")
                                    ^
[error] sbt.compiler.EvalException: Type error in expression
[error] sbt.compiler.EvalException: Type error in expression
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

Any idea why this is happening? Trying to load scalaz-zio fails with a similar error.

**Comment by mijicd** [comment]
@fthomas as far as I can see [sbt-explicit-dependencies](https://github.com/cb372/sbt-explicit-dependencies) is making problems here. I will exclude this plugin from the project and let's try again. I guess the similar situation happens for `scalaz-zio`.

/cc @jdegoes ^

**Comment by fthomas** [comment]
scala-steward can now again load the build.

Btw, this is known problem: https://github.com/cb372/sbt-explicit-dependencies/issues/33

**Comment by mijicd** [comment]
I will try out the suggested workaround. Maybe it's better to wait for the proper fix before merging it back into the codebase.

**Pull request merged**
