### PR TITLE
Added --process-timeout option

### PR DESCRIPTION
**Pull request by tkawachi**
It replaces the hardcoded 10 minutes timeout. The default timeout is left unchanged.

### CODE REVIEW

**Comment by fthomas** [comment]
This LGTM, thanks @tkawachi! I've only one request, could you rename `timeout` to `processTimeout`. I think that `timout` is a tad too generic.

I'm also wondering why you want to have it configurable. Are the 10 minutes too low or too high for you? Should we have a better default?

**Comment by tkawachi** [comment]
`processTimeout` seems a good naming 👍 .

Yes, 10 minutes is too short for our usecase.  I can't say the best, but I suppose it make sense to make it configurable.

**Comment by fthomas** [comment]
Can you say which process takes more than 10 minutes? I've added the timeout for hanging scalafix migrations which never completed. So the 10 minutes are kind of arbitrary. I've never seen a process that completed which took more than ~5 minutes.

**Comment by tkawachi** [comment]
How can I investigate? The following is the log of timeout. Can you figure it out?

```
2019-08-15 05:43:38,919 ERROR ──────────── Nurture foo/bar/backend ──────────── failed
java.util.concurrent.TimeoutException: 'firejail --whitelist=/builds/Library/scala-steward-run/workspace/repos/foo/bar/backend sbt -batch -no-colors ;set every credentials := Nil;dependencyUpdates;reload plugins;dependencyUpdates' timed out after 10 minutes
Warning: an existing sandbox was detected. sbt will run without any additional sandboxing features
irejail sbt -batch -no-colors ;set every credentials := Nil;dependencyUpdates;reload plugins;dependencyUpdates Getting org.scala-sbt sbt 0.13.17  (this may take some time)...
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.17/jars/sbt.jar ...
	[SUCCESSFUL ] org.scala-sbt#sbt;0.13.17!sbt.jar (3646ms)
downloading https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.10.7/scala-library-2.10.7.jar ...
(snip)
	[SUCCESSFUL ] org.fusesource.jansi#jansi;1.4!jansi.jar (436ms)
:: retrieving :: org.scala-sbt#boot-scala
	confs: [default]
	5 artifacts copied, 0 already retrieved (24560kB/26ms)
[info] Loading global plugins from /root/.sbt/0.13/plugins
[info] Updating {file:/root/.sbt/0.13/plugins/}global-plugins...
[info] Resolving com.timushev.sbt#sbt-updates;0.4.2 ...
(snip)
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.timushev.sbt/sbt-updates/scala_2.10/sbt_0.13/0.4.2/srcs/sbt-updates-sources.jar ...
[info] 	[SUCCESSFUL ] com.timushev.sbt#sbt-updates;0.4.2!sbt-updates.jar(src) (3206ms)
[info] downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.timushev.sbt/sbt-updates/scala_2.10/sbt_0.13/0.4.2/docs/sbt-updates-javadoc.jar ...
[info] 	[SUCCESSFUL ] com.timushev.sbt#sbt-updates;0.4.2!sbt-updates.jar(doc) (3864ms)
[info] downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.timushev.sbt/sbt-updates/scala_2.10/sbt_0.13/0.4.2/jars/sbt-updates.jar ...
[info] 	[SUCCESSFUL ] com.timushev.sbt#sbt-updates;0.4.2!sbt-updates.jar (3576ms)
[info] Done updating.
[info] Compiling 1 Scala source to /root/.sbt/0.13/plugins/target/scala-2.10/sbt-0.13/classes...
[info] 'compiler-interface' not yet compiled for Scala 2.10.7. Compiling...
[info]   Compilation completed in 6.325 s
[info] Loading project definition from /builds/Library/scala-steward-run/workspace/repos/foo/bar/backend/project
[info] Updating {file:/builds/Library/scala-steward-run/workspace/repos/foo/bar/backend/project/}backend-build...
[info] Resolving org.scala-sbt#global-plugins;0.0 ...
(snip)
[info] Resolving com.typesafe.akka#akka-actor_2.10;2.3.11 ...
	at org.scalasteward.core.io.process$.$anonfun$slurp$12(process.scala:53)
	at cats.syntax.FlatMapOps$.$anonfun$$greater$greater$1(flatMap.scala:33)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:139)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:355)
	at cats.effect.internals.IORunLoop$RestartCallback.run(IORunLoop.scala:366)
	at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:70)
	at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:36)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
	at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:44)
	at cats.effect.internals.ForwardCancelable.loop$1(ForwardCancelable.scala:46)
	at cats.effect.internals.ForwardCancelable.$anonfun$cancel$1(ForwardCancelable.scala:52)
	at cats.effect.internals.ForwardCancelable.$anonfun$cancel$1$adapted(ForwardCancelable.scala:52)
	at cats.effect.internals.IORunLoop$RestartCallback.start(IORunLoop.scala:341)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:119)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:355)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:376)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:316)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:136)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:355)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:376)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:316)
	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
2019-08-15 05:43:38,920 INFO  ──────────── Total time: foo/bar/backend: 10m 1s 817ms ────────────
```

**Comment by fthomas** [comment]
I was just interested in this line:
```
java.util.concurrent.TimeoutException: 'firejail --whitelist=/builds/Library/scala-steward-run/workspace/repos/foo/bar/backend sbt -batch -no-colors ;set every credentials := Nil;dependencyUpdates;reload plugins;dependencyUpdates' timed out after 10 minutes
```

It seems that just loading the build (and resolving dependencies) takes more than 10 minutes. Thanks for the info.

**Comment by tkawachi** [comment]
Thank you for merging! @fthomas

**Pull request merged**
