### PR TITLE
Add vectos/formulation

### PR DESCRIPTION
**Pull request by Fristi**
Cool idea :-) 

Have you thought about integrating with Dependabot?

### CODE REVIEW

**Comment by fthomas** [comment]
@Fristi What is Dependabot?

**Comment by Fristi** [comment]
Automated dependency updates for a lot languages, except Scala (work in progress I believe)

https://dependabot.com/

**Comment by fthomas** [comment]
Thanks for the link. I think they should hire me. :-)

Will check later if that can be integrated somehow.

**Comment by fthomas** [comment]
@Fristi scala-steward is only a few days old and very much WIP so if you see something odd or if it behaves badly, feel free to complain about it.

**Comment by Fristi** [comment]
Sure I'll let you know. I had this idea also for a while 👍So far so good

**Pull request merged**
