### PR TITLE
Add krasserm/streamz to repos list

### PR DESCRIPTION
**Pull request by Daenyth**

### CODE REVIEW

**Comment by fthomas** [comment]
@Daenyth Have you checked with the maintainer(s) of streamz if they are OK with adding it here. I'd like to avoid flooding projects with pull requests without their consent.

**Comment by Daenyth** [comment]
I'm now the primary maintainer - just waiting on the github transfer.

I'm also fine on not merging this immediately - I have an open branch upgrading dependencies, so it may be easier to wait until that's merged before enabling steward

**Comment by fthomas** [comment]
Ok. Just ping me when I should merge this. I'm also okay with merging this right now.

**Comment by fthomas** [comment]
Closing because the repos.md file for the public Scala Steward instance has been moved to https://github.com/scala-steward-org/repos/blob/master/repos.md. If you still want Scala Steward to keep this project up-to-date, please add it there.

**Pull request closed without merging**
